name: pet-adoption automated tests
run-name: ${{ github.actor }} is testing out pet-adoption automated tests
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  Run-Test-Suite:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04]
        node-version: [16.x]
      fail-fast: false
        
    steps:
    - run: echo "This job is now running on a ${{ matrix.os }}"
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    #Check out the latest code from repository
    - name: Check out the latest code from repository.
      uses: actions/checkout@v4

    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}

    #Setup Node.js environment
    - name: Setup Node.js ${{ matrix.node-version }} on ${{ runner.os }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    #Install frontend dependencies
    - name: Install frontend dependencies
      run: npm install

    #Install backend dependencies
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install
 
    #Run test suite for backend
    - name: Run test suite backend
      working-directory: ./backend
      run: |
         npm test
      env: 
        APP_KEYS: ${{ secrets.APP_KEYS }}
        API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
        ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
        TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    #Run test suite
    - name: Run test suite frontend
      env:
          APP_KEYS: ${{ secrets.APP_KEYS }}              
          API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}  
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }} 
          TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }} 
          JWT_SECRET: ${{ secrets.JWT_SECRET }}        
      run: npm test
   
    - run: echo "This job's status is ${{ job.status }}."
